---
functional:
  - Пользователь должен иметь возможность зарегистрироваться и войти на сайт при
    помощи Github, Discord или email
  - Пользователь должен иметь возможность восстановить пароль при помощи кнопки
    «forgot your password?»
  - Пользователь должен иметь возможность выбрать уровень сложности игры
  - Пользователь должен иметь возможность создать игру с ботом или другим
    пользователем
  - Пользователь должен иметь возможность выбрать длительность игры
  - Пользователь должен иметь возможность выбрать любую задачу или сыграть в
    случайную
  - Пользователь должен иметь возможность участвовать в турнирах, созданных
    другими игроками
  - Пользователь должен иметь возможность поделиться ссылкой для совместной игры
    с друзьями
  - Пользователь должен иметь возможность видеть написание кода у соперника
  - Пользователь должен иметь возможность выбора языка текста задачи
  - Пользователь должен иметь возможность изменить используемый язык
    программирования в своем профиле
  - Пользователь должен иметь возможность изменить язык программирования во
    время матча
  - Пользователь должен иметь возможность следить за игрой других пользователей
    онлайн
  - Пользователь должен иметь возможность смотреть за матчем других игроков
  - Пользователь должен иметь возможность написать сообщения в общем чате, чате
    игры, личное сообщение другому игроку
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован
    для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями
    браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например,
    1000 одновременных пользователей)
implicit:
  - Игра должна завершаться либо победой одого из игроков, либо ничьей
  - Пользователь должен иметь возможность получать обратную связь и помощь
  - Интерфейс сайта должен иметь возможность поддерживать русский язык
  - Проверка решений осуществляется автоматически по тестам
  - Пользователь должен иметь возможность прекратить игру досрочно или
    перезагрузить её
  - Пользователь не должен иметь возможность копировать код соперника
  - Пользователь не должен иметь возможность вставлять скопированный код из
    сторонних источников в окно решения
